In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_breast_cancer

In [2]:
df = load_breast_cancer()
df

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
df['data']

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
x = pd.DataFrame(df['data'], columns = df.feature_names)
x.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [5]:
y = df['target']

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.2, random_state= 0)

In [7]:
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train, y_train)
y_pred = dt_model.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89        47
           1       0.97      0.87      0.91        67

    accuracy                           0.90       114
   macro avg       0.90      0.91      0.90       114
weighted avg       0.91      0.90      0.90       114



## **PCA (Dimensionality Reduction)**

In [27]:
from sklearn.decomposition import PCA # ----> supervised, unsupervised

In [28]:
pca_model = PCA(n_components= 5)
x_train_pca = pca_model.fit_transform(x_train)
x_test_pca = pca_model.transform(x_test)

In [29]:
x_train_pca.shape

(455, 5)

In [30]:
pca_model.explained_variance_ratio_.sum()

0.9999887408181112

In [31]:
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train_pca, y_train)
y_pred = dt_model.predict(x_test_pca)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.96      0.93        47
           1       0.97      0.93      0.95        67

    accuracy                           0.94       114
   macro avg       0.93      0.94      0.94       114
weighted avg       0.94      0.94      0.94       114



## **Feature Selection**

### **1- Information Gain**

In [32]:
from sklearn.feature_selection import mutual_info_classif, mutual_info_regression 

In [35]:
#train info gain on all data
info_gain = mutual_info_classif(df.data, y)

In [36]:
info_gain

array([0.36669482, 0.09935323, 0.40314026, 0.3585625 , 0.0728826 ,
       0.21140795, 0.37253331, 0.43864535, 0.06557657, 0.00786283,
       0.24652257, 0.        , 0.27338504, 0.34140167, 0.01535981,
       0.07572279, 0.11678957, 0.12766802, 0.01009603, 0.03826873,
       0.45267808, 0.12118215, 0.47300275, 0.46487614, 0.10106338,
       0.22497027, 0.31650826, 0.43873132, 0.08996695, 0.06835822])

In [37]:
for feature, gain in enumerate(info_gain):
    print(f'Information Gain for feature {feature}:, ', gain)

Information Gain for feature 0:,  0.36669481733590836
Information Gain for feature 1:,  0.09935322744529951
Information Gain for feature 2:,  0.40314025502735507
Information Gain for feature 3:,  0.3585625023031058
Information Gain for feature 4:,  0.07288260268293256
Information Gain for feature 5:,  0.21140794592164602
Information Gain for feature 6:,  0.3725333113276481
Information Gain for feature 7:,  0.43864534513999387
Information Gain for feature 8:,  0.06557657216593626
Information Gain for feature 9:,  0.007862827287396401
Information Gain for feature 10:,  0.24652256590357347
Information Gain for feature 11:,  0.0
Information Gain for feature 12:,  0.27338504375974493
Information Gain for feature 13:,  0.34140167434078506
Information Gain for feature 14:,  0.015359807828145389
Information Gain for feature 15:,  0.07572278987600423
Information Gain for feature 16:,  0.11678957456351924
Information Gain for feature 17:,  0.127668019522863
Information Gain for feature 18:,  0.0

In [43]:
k = 5
top_k = np.argsort(info_gain)[-k:]
print(top_k)

[ 7 27 20 23 22]


In [44]:
x_train, x_test, y_train, y_test = train_test_split(x.values ,y, test_size= 0.2, random_state= 0)

In [45]:
x_train_gain = x_train[:, top_k]
x_test_gain = x_test[:, top_k]

In [46]:
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train_gain, y_train)
y_pred = dt_model.predict(x_test_gain)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.96      0.93        47
           1       0.97      0.93      0.95        67

    accuracy                           0.94       114
   macro avg       0.93      0.94      0.94       114
weighted avg       0.94      0.94      0.94       114



### **2- Chi-square Test**

In [47]:
from sklearn.feature_selection import SelectKBest, chi2

In [49]:
chi_square = SelectKBest(chi2, k =5) 

In [50]:
x_train, x_test, y_train, y_test = train_test_split(x ,y, test_size= 0.2, random_state= 0)

In [51]:
x_train_chi = chi_square.fit_transform(x_train, y_train)
x_test_chi = chi_square.transform(x_test)

In [52]:
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train_chi, y_train)
y_pred = dt_model.predict(x_test_chi)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93        47
           1       0.95      0.94      0.95        67

    accuracy                           0.94       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.94      0.94      0.94       114



In [53]:
chi_square.get_support(indices= True)

array([ 2,  3, 13, 22, 23], dtype=int64)

In [54]:
df['feature_names'][chi_square.get_support(indices= True)]

array(['mean perimeter', 'mean area', 'area error', 'worst perimeter',
       'worst area'], dtype='<U23')

### **3- Fisher's Score**

In [55]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis #LDA

In [57]:
lda = LinearDiscriminantAnalysis(n_components= 1) #n_classes - 1
x_train_lda = lda.fit_transform(x_train, y_train) 
x_test_lda = lda.transform(x_test)

In [58]:
x_train_lda

array([[-2.07001845],
       [-0.62082166],
       [-0.43720889],
       [-1.61228271],
       [-0.74309534],
       [-1.89632029],
       [-0.40453781],
       [-1.83844638],
       [ 1.49977352],
       [-0.60088194],
       [ 4.02929963],
       [-0.25609167],
       [ 0.05771645],
       [-2.04316215],
       [-2.18245395],
       [-2.31857982],
       [ 1.99807578],
       [-1.63157206],
       [-1.99980507],
       [-0.22097197],
       [-0.16316866],
       [-2.92878114],
       [ 0.08925773],
       [ 0.10009211],
       [ 3.91842384],
       [-2.48307566],
       [-1.60856734],
       [-1.1841597 ],
       [ 4.07152369],
       [-1.02692867],
       [-1.64673126],
       [ 3.10448622],
       [-1.16113199],
       [ 0.48822364],
       [-1.3672863 ],
       [-1.40757071],
       [-1.43952906],
       [-1.26611178],
       [-0.69405747],
       [-0.53417834],
       [-2.59021546],
       [ 1.5209398 ],
       [-0.53716989],
       [ 1.23218288],
       [-1.78190376],
       [ 3

In [59]:
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train_lda, y_train)
y_pred = dt_model.predict(x_test_lda)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.94      0.95        47
           1       0.96      0.97      0.96        67

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



### **4- Variance Threshold**

In [60]:
from sklearn.feature_selection import VarianceThreshold

In [67]:
variance_threshold = VarianceThreshold(threshold=0.4)
x_train_v = variance_threshold.fit_transform(x_train, y_train)
x_test_v = variance_threshold.transform(x_test)

In [68]:
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train_v, y_train)
y_pred = dt_model.predict(x_test_v)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94        47
           1       0.96      0.96      0.96        67

    accuracy                           0.95       114
   macro avg       0.95      0.95      0.95       114
weighted avg       0.95      0.95      0.95       114



### **5- The mean absolute difference (MAD)**

In [69]:
x = df.data
def mad(x):
    mean = np.mean(x)
    return np.mean(np.abs(x - mean))

In [70]:
mad_values = np.apply_along_axis(mad, axis = 0, arr = x)
mad_values

array([2.75188776e+00, 3.38496465e+00, 1.90325780e+01, 2.63483384e+02,
       1.11609886e-02, 4.11052402e-02, 6.25558942e-02, 3.14597998e-02,
       2.11457581e-02, 5.30645353e-03, 1.89284531e-01, 4.08740215e-01,
       1.33252531e+00, 2.71965065e+01, 2.12290566e-03, 1.31384253e-02,
       1.86080085e-02, 4.52792317e-03, 5.81924415e-03, 1.66415113e-03,
       3.78985656e+00, 4.91182490e+00, 2.64654371e+01, 4.23879453e+02,
       1.79555995e-02, 1.19683744e-01, 1.64699576e-01, 5.49961343e-02,
       4.48711210e-02, 1.34096668e-02])

In [71]:
threshold = 4
selected_features = np.where(mad_values > threshold)[0]

In [72]:
selected_features

array([ 2,  3, 13, 21, 22, 23], dtype=int64)

In [73]:
x = pd.DataFrame(df['data'], columns = df.feature_names)
x.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [74]:
new_x = x.iloc[:, selected_features]

In [75]:
new_x.head()

mean perimeter  mean area  area error  worst texture  worst perimeter  \
0          122.80     1001.0      153.40          17.33           184.60   
1          132.90     1326.0       74.08          23.41           158.80   
2          130.00     1203.0       94.03          25.53           152.50   
3           77.58      386.1       27.23          26.50            98.87   
4          135.10     1297.0       94.44          16.67           152.20   

   worst area  
0      2019.0  
1      1956.0  
2      1709.0  
3       567.7  
4      1575.0

In [76]:
x_train, x_test, y_train, y_test = train_test_split(new_x,y, test_size= 0.25, random_state=42)

In [78]:
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train, y_train)
y_pred = dt_model.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.87      0.89        54
           1       0.92      0.94      0.93        89

    accuracy                           0.92       143
   macro avg       0.91      0.91      0.91       143
weighted avg       0.92      0.92      0.92       143

